import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { QueryProvider } from './providers/query-provider'
import { ReactNode } from 'react'
import { Header } from '@/widgets/header'
import { SidebarList } from '@/shared/ui/sidebar/SidbarList'
import s from './Layout.module.css'

const interSans = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
})

export const metadata: Metadata = {
  title: 'Snaptix',
  description: 'Generated by create Snaptix',
}

export default function RootLayout({ children }: Readonly<{ children: ReactNode }>) {
  const isAuth = true

  return (
    <html lang="en">
      <body className={`${interSans.variable} antialiased`}>
        <QueryProvider>
          <Header isAuth={isAuth} />
          <div className={s.content}>
            {isAuth && <SidebarList />}
            <main className={s.main}>{children}</main>
          </div>
        </QueryProvider>
      </body>
    </html>
  )
}
